-- Debug utility: print/log current radio frequencies for a unit
function ATC.debugPrintRadioFrequencies(unitName)
    local freqs = ATC.getRadioFrequencies(unitName)
    local msg = "[ATC DEBUG] Radio frequencies for '" .. tostring(unitName) .. "': "
    if not freqs or next(freqs) == nil then
        msg = msg .. "none found"
    else
        local parts = {}
        for idx, mhz in pairs(freqs) do
            parts[#parts+1] = string.format("R%d=%.3f MHz", idx, mhz)
        end
        msg = msg .. table.concat(parts, ", ")
    end
    if ATC and ATC.log then
        ATC.log(msg)
    end
    if trigger and trigger.action and trigger.action.outText then
        trigger.action.outText(msg, 10)
    end
    return msg
end
-- Extract tuned radio frequencies for a given unit (player aircraft).
-- Primary source: ATC._radioFreqs populated by the export hook via LoGetSelfData /
-- GetDevice scan. The hook pushes data under the DCS pilot name (net.get_name),
-- the aircraft unit name (sd.UnitName), and the aircraft type (sd.Name) as fallback.
-- Lookup order: unit name -> pilot name -> type name (type is last resort; unreliable
-- when multiple aircraft of the same type are airborne).
function ATC.getRadioFrequencies(unitName)
    if ATC._radioFreqs then
        -- 1. Direct match by DCS unit/mission name
        local direct = ATC._radioFreqs[unitName]
        if direct and type(direct) == "table" and next(direct) ~= nil then
            return direct
        end
        local unit = Unit.getByName(unitName)
        if unit and unit:isExist() then
            -- 2. Match by DCS pilot/player name (pushed by export hook via net.get_name)
            local ok_pn, playerName = pcall(function() return unit:getPlayerName() end)
            if ok_pn and type(playerName) == "string" and playerName ~= "" then
                local byPlayer = ATC._radioFreqs[playerName]
                if byPlayer and type(byPlayer) == "table" and next(byPlayer) ~= nil then
                    return byPlayer
                end
            end
            -- 3. Last-resort: aircraft type name (LoGetSelfData().Name)
            local ok_tn, typeName = pcall(function() return unit:getTypeName() end)
            if ok_tn and type(typeName) == "string" then
                local byType = ATC._radioFreqs[typeName]
                if byType and type(byType) == "table" and next(byType) ~= nil then
                    return byType
                end
            end
        end
    end
    return {}
end
_ATC_BASE = _ATC_BASE or ""  -- base path set by hook
ATC = ATC or {}
local _runwaySnapshot = ATC.runways
ATC.runways = ATC.runways or {}

-- Ensure all airfields are registered under both original and normalized keys
local function _registerNormalizedRunways()
    local normalize = function(name)
        return string.lower(name):gsub("[^%w]", "")
    end
    local toAdd = {}
    for key, value in pairs(ATC.runways) do
        local norm = normalize(key)
        if norm ~= key and ATC.runways[norm] == nil then
            toAdd[#toAdd+1] = {norm, value}
        end
    end
    for _, pair in ipairs(toAdd) do
        ATC.runways[pair[1]] = pair[2]
    end
end

-- Defer normalization until after all airfield files are loaded
ATC.deferRegisterNormalizedRunways = _registerNormalizedRunways

ATC = ATC or {}
ATC._timersStarted = nil
ATC._notificationShown = nil
-- PHRASE_DUR_START (auto-generated by Generate-Phrases.ps1 - do not edit manually)
ATC._phraseDur = {
    ["adam/abbas"] = 0.84,
    ["adam/abeam-the-threshold"] = 1.49,
    ["adam/abu"] = 0.79,
    ["adam/adana"] = 0.88,
    ["adam/adler"] = 0.74,
    ["adam/ain"] = 0.6,
    ["adam/airspeed-critically-low"] = 1.58,
    ["adam/akrotiri"] = 1.11,
    ["adam/al"] = 0.6,
    ["adam/alpha"] = 0.74,
    ["adam/anapa"] = 0.88,
    ["adam/and"] = 0.65,
    ["adam/approach"] = 0.88,
    ["adam/are"] = 0.7,
    ["adam/at"] = 0.6,
    ["adam/baghdad"] = 1.11,
    ["adam/bagram"] = 0.93,
    ["adam/bandar"] = 0.79,
    ["adam/base-heading"] = 1.07,
    ["adam/bateen"] = 0.98,
    ["adam/batumi"] = 0.93,
    ["adam/beirut"] = 0.84,
    ["adam/beslan"] = 0.93,
    ["adam/bone"] = 0.88,
    ["adam/bravo"] = 0.84,
    ["adam/cairo"] = 0.88,
    ["adam/carpiquet"] = 1.02,
    ["adam/charlie"] = 0.84,
    ["adam/check-gear-down-and-locked"] = 1.63,
    ["adam/chevy"] = 0.74,
    ["adam/cleared-for-takeoff"] = 1.35,
    ["adam/cleared-for-the-approach"] = 1.49,
    ["adam/cleared-to-land"] = 1.3,
    ["adam/climb"] = 0.84,
    ["adam/climb-immediately-runway-heading"] = 2.04,
    ["adam/climb-to"] = 0.98,
    ["adam/climb-to-5000"] = 1.53,
    ["adam/cobra"] = 0.88,
    ["adam/colt"] = 0.74,
    ["adam/contact"] = 0.93,
    ["adam/contact-ground"] = 1.95,
    ["adam/contact-tower"] = 1.16,
    ["adam/continue-approach"] = 1.11,
    ["adam/correct-approach"] = 3.62,
    ["adam/crosswind"] = 1.07,
    ["adam/damascus"] = 1.07,
    ["adam/david"] = 0.84,
    ["adam/delta"] = 0.84,
    ["adam/departure"] = 0.98,
    ["adam/descend"] = 1.02,
    ["adam/descend-to"] = 1.02,
    ["adam/devil"] = 0.7,
    ["adam/dhabi"] = 0.84,
    ["adam/dhafra"] = 1.02,
    ["adam/dodge"] = 0.88,
    ["adam/dubai"] = 0.93,
    ["adam/dude"] = 0.79,
    ["adam/eagle"] = 0.79,
    ["adam/east"] = 0.78,
    ["adam/echo"] = 0.7,
    ["adam/eight"] = 0.65,
    ["adam/eilat"] = 0.74,
    ["adam/enfield"] = 0.93,
    ["adam/erbil"] = 0.74,
    ["adam/established-on-final"] = 1.58,
    ["adam/evreux"] = 0.84,
    ["adam/expect"] = 0.93,
    ["adam/expect-vectors-to-runway"] = 1.58,
    ["adam/feet"] = 0.7,
    ["adam/five"] = 0.88,
    ["adam/fly-heading"] = 1.02,
    ["adam/fly-heading-climb"] = 1.07,
    ["adam/follow"] = 0.74,
    ["adam/for"] = 0.6,
    ["adam/ford"] = 0.84,
    ["adam/four"] = 0.79,
    ["adam/foxtrot"] = 1.07,
    ["adam/from"] = 0.7,
    ["adam/from-threshold"] = 1.25,
    ["adam/fujairah"] = 1.02,
    ["adam/gelendzhik"] = 1.02,
    ["adam/ghost"] = 0.93,
    ["adam/go-around-go-around"] = 1.39,
    ["adam/golf"] = 0.79,
    ["adam/good-afternoon"] = 1.07,
    ["adam/good-evening"] = 0.98,
    ["adam/good-morning"] = 0.93,
    ["adam/ground"] = 0.98,
    ["adam/gudauta"] = 1.02,
    ["adam/haifa"] = 0.84,
    ["adam/halab"] = 0.93,
    ["adam/hatay"] = 0.84,
    ["adam/hawg"] = 0.88,
    ["adam/hawk"] = 0.84,
    ["adam/hold"] = 0.88,
    ["adam/hotel"] = 0.88,
    ["adam/hundred"] = 0.84,
    ["adam/incirlik"] = 0.98,
    ["adam/increase-speed-to"] = 1.44,
    ["adam/india"] = 0.84,
    ["adam/initial"] = 0.93,
    ["adam/jedi"] = 0.84,
    ["adam/jiroft"] = 1.07,
    ["adam/juliet"] = 0.98,
    ["adam/kabul"] = 0.84,
    ["adam/kandahar"] = 1.07,
    ["adam/kerman"] = 0.88,
    ["adam/kilo"] = 0.84,
    ["adam/kirkuk"] = 0.84,
    ["adam/kish"] = 0.79,
    ["adam/knots"] = 0.84,
    ["adam/kobuleti"] = 1.02,
    ["adam/kolkhi"] = 0.88,
    ["adam/krasnodar"] = 1.16,
    ["adam/krymsk"] = 0.93,
    ["adam/kutaisi"] = 1.11,
    ["adam/lancer"] = 0.93,
    ["adam/landing"] = 0.97,
    ["adam/lar"] = 0.7,
    ["adam/lavan"] = 0.93,
    ["adam/left"] = 0.79,
    ["adam/lima"] = 0.79,
    ["adam/lincoln"] = 0.84,
    ["adam/lobo"] = 0.88,
    ["adam/lochini"] = 0.93,
    ["adam/maintain"] = 0.98,
    ["adam/mako"] = 0.93,
    ["adam/maktoum"] = 1.07,
    ["adam/maykop"] = 0.93,
    ["adam/MHz"] = 1.02,
    ["adam/mike"] = 0.79,
    ["adam/mineralnye"] = 1.16,
    ["adam/minhad"] = 1.02,
    ["adam/missed-approach"] = 1.16,
    ["adam/mozdok"] = 0.98,
    ["adam/murmansk"] = 1.11,
    ["adam/musa"] = 0.84,
    ["adam/nalchik"] = 1.02,
    ["adam/nautical-miles"] = 1.39,
    ["adam/niner"] = 0.79,
    ["adam/normandy"] = 0.93,
    ["adam/north"] = 0.84,
    ["adam/northeast"] = 1.07,
    ["adam/northwest"] = 1.1,
    ["adam/november"] = 0.93,
    ["adam/novorossiysk"] = 1.35,
    ["adam/number"] = 0.5,
    ["adam/of"] = 0.6,
    ["adam/olds"] = 0.74,
    ["adam/on"] = 0.74,
    ["adam/on-base-runway"] = 1.3,
    ["adam/on-downwind"] = 1.25,
    ["adam/one"] = 0.65,
    ["adam/on-this-frequency"] = 1.3,
    ["adam/oscar"] = 0.74,
    ["adam/out"] = 0.65,
    ["adam/ovda"] = 0.74,
    ["adam/panther"] = 0.84,
    ["adam/papa"] = 0.79,
    ["adam/pashkovsky"] = 1.07,
    ["adam/point"] = 0.78,
    ["adam/pontiac"] = 1.07,
    ["adam/qeshm"] = 0.88,
    ["adam/quebec"] = 0.88,
    ["adam/radar-contact"] = 1.21,
    ["adam/ramat"] = 0.84,
    ["adam/reaper"] = 0.79,
    ["adam/rebel"] = 0.7,
    ["adam/reduce-speed-to"] = 1.25,
    ["adam/report-15-NM"] = 2,
    ["adam/report-final"] = 1.11,
    ["adam/return-to-pattern"] = 2.09,
    ["adam/right"] = 0.74,
    ["adam/romeo"] = 0.93,
    ["adam/runway"] = 0.93,
    ["adam/runway-clear"] = 1.11,
    ["adam/runway-occupied"] = 1.44,
    ["adam/sakirpasa"] = 1.25,
    ["adam/senaki"] = 1.07,
    ["adam/seven"] = 0.74,
    ["adam/sharjah"] = 0.88,
    ["adam/shark"] = 0.84,
    ["adam/shiraz"] = 0.98,
    ["adam/sierra"] = 0.88,
    ["adam/sirri"] = 0.84,
    ["adam/six"] = 0.79,
    ["adam/slow-to-approach-speed"] = 1.39,
    ["adam/sniper"] = 0.84,
    ["adam/sochi"] = 0.84,
    ["adam/soganlug"] = 1.11,
    ["adam/south"] = 0.84,
    ["adam/southeast"] = 1.07,
    ["adam/southwest"] = 1.2,
    ["adam/speed"] = 0.88,
    ["adam/springfield"] = 1.07,
    ["adam/startup-clearance"] = 1.72,
    ["adam/storm"] = 0.98,
    ["adam/straight-in"] = 0.93,
    ["adam/sukhumi"] = 0.98,
    ["adam/taftanaz"] = 1.21,
    ["adam/talon"] = 0.79,
    ["adam/tango"] = 0.93,
    ["adam/tbilisi"] = 1.07,
    ["adam/thousand"] = 0.97,
    ["adam/three"] = 0.79,
    ["adam/tiger"] = 0.84,
    ["adam/to"] = 0.56,
    ["adam/tower"] = 0.79,
    ["adam/traffic"] = 0.93,
    ["adam/tunb"] = 0.88,
    ["adam/turn-final-heading"] = 1.39,
    ["adam/turn-left-heading"] = 1.25,
    ["adam/turn-right-heading"] = 1.25,
    ["adam/two"] = 0.7,
    ["adam/uniform"] = 0.93,
    ["adam/uzi"] = 0.74,
    ["adam/vacate-runway"] = 2.46,
    ["adam/vaziani"] = 1.21,
    ["adam/venom"] = 0.84,
    ["adam/victor"] = 0.84,
    ["adam/viper"] = 0.79,
    ["adam/vityazevo"] = 1.11,
    ["adam/vody"] = 0.84,
    ["adam/weasel"] = 0.88,
    ["adam/west"] = 0.97,
    ["adam/whiskey"] = 0.79,
    ["adam/wind"] = 0.88,
    ["adam/wind-calm"] = 1.3,
    ["adam/witch"] = 0.84,
    ["adam/with"] = 0.7,
    ["adam/wolf"] = 0.84,
    ["adam/xray"] = 0.84,
    ["adam/yankee"] = 0.79,
    ["adam/you"] = 0.56,
    ["adam/you-are-number"] = 1.21,
    ["adam/zero"] = 0.7,
    ["adam/zulu"] = 0.84,
    ["alice/abbas"] = 0.6,
    ["alice/abeam-the-threshold"] = 1.44,
    ["alice/abu"] = 0.6,
    ["alice/adana"] = 0.84,
    ["alice/adler"] = 0.51,
    ["alice/ain"] = 0.33,
    ["alice/airspeed-critically-low"] = 1.63,
    ["alice/akrotiri"] = 1.16,
    ["alice/al"] = 0.51,
    ["alice/alpha"] = 0.51,
    ["alice/anapa"] = 0.79,
    ["alice/and"] = 0.74,
    ["alice/approach"] = 0.88,
    ["alice/are"] = 0.42,
    ["alice/at"] = 0.46,
    ["alice/baghdad"] = 1.02,
    ["alice/bagram"] = 0.7,
    ["alice/bandar"] = 0.65,
    ["alice/base-heading"] = 1.07,
    ["alice/bateen"] = 0.74,
    ["alice/batumi"] = 1.02,
    ["alice/beirut"] = 0.84,
    ["alice/beslan"] = 0.93,
    ["alice/bone"] = 0.84,
    ["alice/bravo"] = 0.74,
    ["alice/cairo"] = 0.65,
    ["alice/carpiquet"] = 0.79,
    ["alice/charlie"] = 0.7,
    ["alice/check-gear-down-and-locked"] = 1.44,
    ["alice/chevy"] = 0.79,
    ["alice/cleared-for-takeoff"] = 1.44,
    ["alice/cleared-for-the-approach"] = 1.63,
    ["alice/cleared-to-land"] = 1.3,
    ["alice/climb"] = 0.84,
    ["alice/climb-immediately-runway-heading"] = 2.14,
    ["alice/climb-to"] = 0.79,
    ["alice/climb-to-5000"] = 2,
    ["alice/cobra"] = 0.88,
    ["alice/colt"] = 0.7,
    ["alice/contact"] = 0.7,
    ["alice/contact-ground"] = 2.37,
    ["alice/contact-tower"] = 1.02,
    ["alice/continue-approach"] = 1.16,
    ["alice/correct-approach"] = 3.3,
    ["alice/crosswind"] = 1.07,
    ["alice/damascus"] = 0.79,
    ["alice/david"] = 0.74,
    ["alice/delta"] = 0.65,
    ["alice/departure"] = 0.84,
    ["alice/descend"] = 0.74,
    ["alice/descend-to"] = 0.88,
    ["alice/devil"] = 0.6,
    ["alice/dhabi"] = 0.84,
    ["alice/dhafra"] = 0.74,
    ["alice/dodge"] = 0.6,
    ["alice/dubai"] = 0.7,
    ["alice/dude"] = 0.74,
    ["alice/eagle"] = 0.79,
    ["alice/east"] = 0.55,
    ["alice/echo"] = 0.56,
    ["alice/eight"] = 0.56,
    ["alice/eilat"] = 0.65,
    ["alice/enfield"] = 0.74,
    ["alice/erbil"] = 0.56,
    ["alice/established-on-final"] = 1.49,
    ["alice/evreux"] = 0.88,
    ["alice/expect"] = 0.88,
    ["alice/expect-vectors-to-runway"] = 1.86,
    ["alice/feet"] = 0.56,
    ["alice/five"] = 0.56,
    ["alice/fly-heading"] = 1.02,
    ["alice/fly-heading-climb"] = 1.02,
    ["alice/follow"] = 0.56,
    ["alice/for"] = 0.46,
    ["alice/ford"] = 0.74,
    ["alice/four"] = 0.46,
    ["alice/foxtrot"] = 0.79,
    ["alice/from"] = 0.65,
    ["alice/from-threshold"] = 1.25,
    ["alice/fujairah"] = 1.02,
    ["alice/gelendzhik"] = 0.88,
    ["alice/ghost"] = 0.7,
    ["alice/go-around-go-around"] = 1.67,
    ["alice/golf"] = 0.79,
    ["alice/good-afternoon"] = 1.02,
    ["alice/good-evening"] = 0.74,
    ["alice/good-morning"] = 0.74,
    ["alice/ground"] = 0.88,
    ["alice/gudauta"] = 0.74,
    ["alice/haifa"] = 0.93,
    ["alice/halab"] = 0.88,
    ["alice/hatay"] = 0.65,
    ["alice/hawg"] = 0.79,
    ["alice/hawk"] = 0.65,
    ["alice/hold"] = 0.79,
    ["alice/hotel"] = 0.74,
    ["alice/hundred"] = 0.86,
    ["alice/incirlik"] = 0.74,
    ["alice/increase-speed-to"] = 1.25,
    ["alice/india"] = 0.7,
    ["alice/initial"] = 0.56,
    ["alice/jedi"] = 0.65,
    ["alice/jiroft"] = 0.6,
    ["alice/juliet"] = 0.98,
    ["alice/kabul"] = 0.65,
    ["alice/kandahar"] = 1.02,
    ["alice/kerman"] = 0.65,
    ["alice/kilo"] = 0.88,
    ["alice/kirkuk"] = 0.65,
    ["alice/kish"] = 0.51,
    ["alice/knots"] = 0.56,
    ["alice/kobuleti"] = 1.11,
    ["alice/kolkhi"] = 0.65,
    ["alice/krasnodar"] = 0.88,
    ["alice/krymsk"] = 0.74,
    ["alice/kutaisi"] = 0.88,
    ["alice/lancer"] = 0.7,
    ["alice/landing"] = 0.65,
    ["alice/lar"] = 0.6,
    ["alice/lavan"] = 0.6,
    ["alice/left"] = 0.79,
    ["alice/lima"] = 0.84,
    ["alice/lincoln"] = 0.56,
    ["alice/lobo"] = 0.65,
    ["alice/lochini"] = 1.02,
    ["alice/maintain"] = 0.93,
    ["alice/mako"] = 0.65,
    ["alice/maktoum"] = 0.7,
    ["alice/maykop"] = 0.7,
    ["alice/MHz"] = 0.79,
    ["alice/mike"] = 0.79,
    ["alice/mineralnye"] = 1.11,
    ["alice/minhad"] = 0.7,
    ["alice/missed-approach"] = 1.35,
    ["alice/mozdok"] = 0.65,
    ["alice/murmansk"] = 0.74,
    ["alice/musa"] = 0.6,
    ["alice/nalchik"] = 0.79,
    ["alice/nautical-miles"] = 1.44,
    ["alice/niner"] = 0.56,
    ["alice/normandy"] = 0.98,
    ["alice/north"] = 0.6,
    ["alice/northeast"] = 0.84,
    ["alice/northwest"] = 0.84,
    ["alice/november"] = 0.74,
    ["alice/novorossiysk"] = 0.93,
    ["alice/number"] = 0.7,
    ["alice/of"] = 0.46,
    ["alice/olds"] = 0.7,
    ["alice/on"] = 0.51,
    ["alice/on-base-runway"] = 1.35,
    ["alice/on-downwind"] = 1.35,
    ["alice/one"] = 0.74,
    ["alice/on-this-frequency"] = 1.35,
    ["alice/oscar"] = 0.56,
    ["alice/out"] = 0.6,
    ["alice/ovda"] = 0.65,
    ["alice/panther"] = 0.74,
    ["alice/papa"] = 0.65,
    ["alice/pashkovsky"] = 1.16,
    ["alice/point"] = 0.84,
    ["alice/pontiac"] = 0.79,
    ["alice/qeshm"] = 0.7,
    ["alice/quebec"] = 0.7,
    ["alice/radar-contact"] = 1.16,
    ["alice/ramat"] = 0.98,
    ["alice/reaper"] = 0.65,
    ["alice/rebel"] = 0.51,
    ["alice/reduce-speed-to"] = 1.25,
    ["alice/report-15-NM"] = 2.14,
    ["alice/report-final"] = 1.02,
    ["alice/return-to-pattern"] = 2.55,
    ["alice/right"] = 0.79,
    ["alice/romeo"] = 0.7,
    ["alice/runway"] = 0.65,
    ["alice/runway-clear"] = 0.98,
    ["alice/runway-occupied"] = 1.35,
    ["alice/sakirpasa"] = 1.25,
    ["alice/senaki"] = 0.79,
    ["alice/seven"] = 0.56,
    ["alice/sharjah"] = 0.88,
    ["alice/shark"] = 0.7,
    ["alice/shiraz"] = 0.65,
    ["alice/sierra"] = 0.65,
    ["alice/sirri"] = 0.84,
    ["alice/six"] = 0.56,
    ["alice/slow-to-approach-speed"] = 1.49,
    ["alice/sniper"] = 0.7,
    ["alice/sochi"] = 0.65,
    ["alice/soganlug"] = 0.88,
    ["alice/south"] = 0.6,
    ["alice/southeast"] = 0.84,
    ["alice/southwest"] = 0.84,
    ["alice/speed"] = 0.84,
    ["alice/springfield"] = 1.07,
    ["alice/startup-clearance"] = 1.76,
    ["alice/storm"] = 0.6,
    ["alice/straight-in"] = 1.02,
    ["alice/sukhumi"] = 1.02,
    ["alice/taftanaz"] = 0.88,
    ["alice/talon"] = 0.65,
    ["alice/tango"] = 0.7,
    ["alice/tbilisi"] = 0.84,
    ["alice/thousand"] = 0.91,
    ["alice/three"] = 0.56,
    ["alice/tiger"] = 0.7,
    ["alice/to"] = 0.46,
    ["alice/tower"] = 0.79,
    ["alice/traffic"] = 0.74,
    ["alice/tunb"] = 0.74,
    ["alice/turn-final-heading"] = 1.11,
    ["alice/turn-left-heading"] = 1.11,
    ["alice/turn-right-heading"] = 1.02,
    ["alice/two"] = 0.42,
    ["alice/uniform"] = 0.88,
    ["alice/uzi"] = 0.7,
    ["alice/vacate-runway"] = 2.37,
    ["alice/vaziani"] = 0.98,
    ["alice/venom"] = 0.6,
    ["alice/victor"] = 0.65,
    ["alice/viper"] = 0.65,
    ["alice/vityazevo"] = 1.11,
    ["alice/vody"] = 0.84,
    ["alice/weasel"] = 0.6,
    ["alice/west"] = 0.6,
    ["alice/whiskey"] = 0.6,
    ["alice/wind"] = 0.56,
    ["alice/wind-calm"] = 1.11,
    ["alice/witch"] = 0.51,
    ["alice/with"] = 0.46,
    ["alice/wolf"] = 0.74,
    ["alice/xray"] = 0.79,
    ["alice/yankee"] = 0.79,
    ["alice/you"] = 0.42,
    ["alice/you-are-number"] = 1.07,
    ["alice/zero"] = 0.65,
    ["alice/zulu"] = 0.6,
    ["daniel/abbas"] = 0.79,
    ["daniel/abeam-the-threshold"] = 1.76,
    ["daniel/abu"] = 0.7,
    ["daniel/adana"] = 0.88,
    ["daniel/adler"] = 0.79,
    ["daniel/ain"] = 0.84,
    ["daniel/airspeed-critically-low"] = 1.9,
    ["daniel/akrotiri"] = 1.21,
    ["daniel/al"] = 0.5,
    ["daniel/alpha"] = 0.79,
    ["daniel/anapa"] = 0.84,
    ["daniel/and"] = 0.7,
    ["daniel/approach"] = 0.93,
    ["daniel/are"] = 0.51,
    ["daniel/at"] = 0.44,
    ["daniel/baghdad"] = 0.98,
    ["daniel/bagram"] = 1.02,
    ["daniel/bandar"] = 0.6,
    ["daniel/base-heading"] = 1.11,
    ["daniel/bateen"] = 1.02,
    ["daniel/batumi"] = 0.98,
    ["daniel/beirut"] = 0.88,
    ["daniel/beslan"] = 0.88,
    ["daniel/bone"] = 0.74,
    ["daniel/bravo"] = 0.88,
    ["daniel/cairo"] = 0.98,
    ["daniel/carpiquet"] = 0.93,
    ["daniel/charlie"] = 0.88,
    ["daniel/check-gear-down-and-locked"] = 2.32,
    ["daniel/chevy"] = 0.84,
    ["daniel/cleared-for-takeoff"] = 1.58,
    ["daniel/cleared-for-the-approach"] = 1.63,
    ["daniel/cleared-to-land"] = 1.35,
    ["daniel/climb"] = 0.88,
    ["daniel/climb-immediately-runway-heading"] = 2.37,
    ["daniel/climb-to"] = 0.88,
    ["daniel/climb-to-5000"] = 2,
    ["daniel/cobra"] = 0.88,
    ["daniel/colt"] = 0.84,
    ["daniel/contact"] = 1.02,
    ["daniel/contact-ground"] = 2.83,
    ["daniel/contact-tower"] = 1.3,
    ["daniel/continue-approach"] = 1.49,
    ["daniel/correct-approach"] = 4.37,
    ["daniel/crosswind"] = 1.16,
    ["daniel/damascus"] = 1.16,
    ["daniel/david"] = 0.84,
    ["daniel/delta"] = 0.88,
    ["daniel/departure"] = 1.02,
    ["daniel/descend"] = 0.93,
    ["daniel/descend-to"] = 1.02,
    ["daniel/devil"] = 0.74,
    ["daniel/dhabi"] = 0.88,
    ["daniel/dhafra"] = 0.88,
    ["daniel/dodge"] = 0.84,
    ["daniel/dubai"] = 0.98,
    ["daniel/dude"] = 0.74,
    ["daniel/eagle"] = 0.74,
    ["daniel/east"] = 0.73,
    ["daniel/echo"] = 0.84,
    ["daniel/eight"] = 0.7,
    ["daniel/eilat"] = 0.74,
    ["daniel/enfield"] = 0.98,
    ["daniel/erbil"] = 0.88,
    ["daniel/established-on-final"] = 1.81,
    ["daniel/evreux"] = 0.98,
    ["daniel/expect"] = 0.98,
    ["daniel/expect-vectors-to-runway"] = 1.9,
    ["daniel/feet"] = 0.7,
    ["daniel/five"] = 0.84,
    ["daniel/fly-heading"] = 1.07,
    ["daniel/fly-heading-climb"] = 1.11,
    ["daniel/follow"] = 0.79,
    ["daniel/for"] = 0.74,
    ["daniel/ford"] = 0.88,
    ["daniel/four"] = 0.84,
    ["daniel/foxtrot"] = 1.02,
    ["daniel/from"] = 0.74,
    ["daniel/from-threshold"] = 1.39,
    ["daniel/fujairah"] = 1.02,
    ["daniel/gelendzhik"] = 1.21,
    ["daniel/ghost"] = 0.93,
    ["daniel/go-around-go-around"] = 1.81,
    ["daniel/golf"] = 0.88,
    ["daniel/good-afternoon"] = 1.16,
    ["daniel/good-evening"] = 0.93,
    ["daniel/good-morning"] = 0.88,
    ["daniel/ground"] = 0.93,
    ["daniel/gudauta"] = 1.02,
    ["daniel/haifa"] = 0.88,
    ["daniel/halab"] = 0.84,
    ["daniel/hatay"] = 0.88,
    ["daniel/hawg"] = 0.88,
    ["daniel/hawk"] = 0.79,
    ["daniel/hold"] = 0.74,
    ["daniel/hotel"] = 0.93,
    ["daniel/hundred"] = 0.91,
    ["daniel/incirlik"] = 1.07,
    ["daniel/increase-speed-to"] = 1.53,
    ["daniel/india"] = 0.88,
    ["daniel/initial"] = 0.84,
    ["daniel/jedi"] = 0.88,
    ["daniel/jiroft"] = 1.07,
    ["daniel/juliet"] = 0.98,
    ["daniel/kabul"] = 0.88,
    ["daniel/kandahar"] = 1.11,
    ["daniel/kerman"] = 0.65,
    ["daniel/kilo"] = 0.84,
    ["daniel/kirkuk"] = 1.02,
    ["daniel/kish"] = 0.74,
    ["daniel/knots"] = 0.88,
    ["daniel/kobuleti"] = 1.11,
    ["daniel/kolkhi"] = 0.88,
    ["daniel/krasnodar"] = 1.21,
    ["daniel/krymsk"] = 0.93,
    ["daniel/kutaisi"] = 0.93,
    ["daniel/lancer"] = 0.88,
    ["daniel/landing"] = 0.91,
    ["daniel/lar"] = 0.74,
    ["daniel/lavan"] = 0.65,
    ["daniel/left"] = 0.79,
    ["daniel/lima"] = 0.79,
    ["daniel/lincoln"] = 0.79,
    ["daniel/lobo"] = 0.88,
    ["daniel/lochini"] = 1.02,
    ["daniel/maintain"] = 1.07,
    ["daniel/mako"] = 0.84,
    ["daniel/maktoum"] = 0.93,
    ["daniel/maykop"] = 0.93,
    ["daniel/MHz"] = 1.21,
    ["daniel/mike"] = 0.7,
    ["daniel/mineralnye"] = 1.25,
    ["daniel/minhad"] = 0.88,
    ["daniel/missed-approach"] = 1.44,
    ["daniel/mozdok"] = 0.88,
    ["daniel/murmansk"] = 1.16,
    ["daniel/musa"] = 0.84,
    ["daniel/nalchik"] = 0.93,
    ["daniel/nautical-miles"] = 1.44,
    ["daniel/niner"] = 0.84,
    ["daniel/normandy"] = 1.02,
    ["daniel/north"] = 0.86,
    ["daniel/northeast"] = 1.15,
    ["daniel/northwest"] = 1.28,
    ["daniel/november"] = 0.98,
    ["daniel/novorossiysk"] = 1.35,
    ["daniel/number"] = 0.88,
    ["daniel/of"] = 0.51,
    ["daniel/olds"] = 0.79,
    ["daniel/on"] = 0.74,
    ["daniel/on-base-runway"] = 1.58,
    ["daniel/on-downwind"] = 1.35,
    ["daniel/one"] = 0.56,
    ["daniel/on-this-frequency"] = 1.49,
    ["daniel/oscar"] = 0.79,
    ["daniel/out"] = 0.6,
    ["daniel/ovda"] = 0.93,
    ["daniel/panther"] = 0.93,
    ["daniel/papa"] = 0.65,
    ["daniel/pashkovsky"] = 1.25,
    ["daniel/point"] = 0.73,
    ["daniel/pontiac"] = 0.93,
    ["daniel/qeshm"] = 0.84,
    ["daniel/quebec"] = 0.93,
    ["daniel/radar-contact"] = 1.44,
    ["daniel/ramat"] = 0.79,
    ["daniel/reaper"] = 0.84,
    ["daniel/rebel"] = 0.7,
    ["daniel/reduce-speed-to"] = 1.63,
    ["daniel/report-15-NM"] = 2.55,
    ["daniel/report-final"] = 1.3,
    ["daniel/return-to-pattern"] = 2.83,
    ["daniel/right"] = 0.7,
    ["daniel/romeo"] = 0.93,
    ["daniel/runway"] = 0.98,
    ["daniel/runway-clear"] = 1.25,
    ["daniel/runway-occupied"] = 1.72,
    ["daniel/sakirpasa"] = 1.3,
    ["daniel/senaki"] = 1.02,
    ["daniel/seven"] = 0.74,
    ["daniel/sharjah"] = 0.93,
    ["daniel/shark"] = 0.88,
    ["daniel/shiraz"] = 0.98,
    ["daniel/sierra"] = 0.98,
    ["daniel/sirri"] = 0.79,
    ["daniel/six"] = 0.88,
    ["daniel/slow-to-approach-speed"] = 1.76,
    ["daniel/sniper"] = 0.88,
    ["daniel/sochi"] = 0.88,
    ["daniel/soganlug"] = 1.11,
    ["daniel/south"] = 0.91,
    ["daniel/southeast"] = 1.07,
    ["daniel/southwest"] = 1.1,
    ["daniel/speed"] = 0.93,
    ["daniel/springfield"] = 1.25,
    ["daniel/startup-clearance"] = 1.95,
    ["daniel/storm"] = 0.93,
    ["daniel/straight-in"] = 0.98,
    ["daniel/sukhumi"] = 1.02,
    ["daniel/taftanaz"] = 1.16,
    ["daniel/talon"] = 0.79,
    ["daniel/tango"] = 0.98,
    ["daniel/tbilisi"] = 1.02,
    ["daniel/thousand"] = 0.91,
    ["daniel/three"] = 0.84,
    ["daniel/tiger"] = 0.84,
    ["daniel/to"] = 0.42,
    ["daniel/tower"] = 0.84,
    ["daniel/traffic"] = 0.84,
    ["daniel/tunb"] = 0.79,
    ["daniel/turn-final-heading"] = 1.76,
    ["daniel/turn-left-heading"] = 1.72,
    ["daniel/turn-right-heading"] = 1.53,
    ["daniel/two"] = 0.84,
    ["daniel/uniform"] = 0.93,
    ["daniel/uzi"] = 1.07,
    ["daniel/vacate-runway"] = 2.69,
    ["daniel/vaziani"] = 1.07,
    ["daniel/venom"] = 0.74,
    ["daniel/victor"] = 0.65,
    ["daniel/viper"] = 0.84,
    ["daniel/vityazevo"] = 1.21,
    ["daniel/vody"] = 0.84,
    ["daniel/weasel"] = 0.84,
    ["daniel/west"] = 0.91,
    ["daniel/whiskey"] = 0.84,
    ["daniel/wind"] = 0.88,
    ["daniel/wind-calm"] = 1.58,
    ["daniel/witch"] = 0.84,
    ["daniel/with"] = 0.7,
    ["daniel/wolf"] = 0.79,
    ["daniel/xray"] = 0.93,
    ["daniel/yankee"] = 0.84,
    ["daniel/you"] = 0.56,
    ["daniel/you-are-number"] = 1.11,
    ["daniel/zero"] = 0.79,
    ["daniel/zulu"] = 0.84,
    ["gary/abbas"] = 0.93,
    ["gary/abeam-the-threshold"] = 1.53,
    ["gary/abu"] = 0.74,
    ["gary/adana"] = 1.02,
    ["gary/adler"] = 0.79,
    ["gary/ain"] = 0.7,
    ["gary/airspeed-critically-low"] = 2,
    ["gary/akrotiri"] = 1.25,
    ["gary/al"] = 0.7,
    ["gary/alpha"] = 0.79,
    ["gary/anapa"] = 0.93,
    ["gary/and"] = 0.74,
    ["gary/approach"] = 0.98,
    ["gary/are"] = 0.6,
    ["gary/at"] = 0.7,
    ["gary/baghdad"] = 1.02,
    ["gary/bagram"] = 1.11,
    ["gary/bandar"] = 0.93,
    ["gary/base-heading"] = 1.11,
    ["gary/bateen"] = 0.98,
    ["gary/batumi"] = 1.07,
    ["gary/beirut"] = 0.93,
    ["gary/beslan"] = 0.98,
    ["gary/bone"] = 0.84,
    ["gary/bravo"] = 0.84,
    ["gary/cairo"] = 0.98,
    ["gary/carpiquet"] = 1.11,
    ["gary/charlie"] = 0.93,
    ["gary/check-gear-down-and-locked"] = 1.76,
    ["gary/chevy"] = 0.88,
    ["gary/cleared-for-takeoff"] = 1.49,
    ["gary/cleared-for-the-approach"] = 1.53,
    ["gary/cleared-to-land"] = 1.39,
    ["gary/climb"] = 0.88,
    ["gary/climb-immediately-runway-heading"] = 2.32,
    ["gary/climb-to"] = 1.21,
    ["gary/climb-to-5000"] = 1.95,
    ["gary/cobra"] = 0.93,
    ["gary/colt"] = 0.84,
    ["gary/contact"] = 1.02,
    ["gary/contact-ground"] = 2.28,
    ["gary/contact-tower"] = 1.39,
    ["gary/continue-approach"] = 1.44,
    ["gary/correct-approach"] = 3.72,
    ["gary/crosswind"] = 1.02,
    ["gary/damascus"] = 1.11,
    ["gary/delta"] = 0.93,
    ["gary/departure"] = 1.07,
    ["gary/descend"] = 1.07,
    ["gary/descend-to"] = 1.25,
    ["gary/devil"] = 0.84,
    ["gary/dhabi"] = 0.88,
    ["gary/dhafra"] = 0.93,
    ["gary/dodge"] = 0.93,
    ["gary/dubai"] = 0.93,
    ["gary/dude"] = 0.84,
    ["gary/eagle"] = 0.84,
    ["gary/east"] = 0.84,
    ["gary/echo"] = 0.84,
    ["gary/eight"] = 0.74,
    ["gary/eilat"] = 0.88,
    ["gary/enfield"] = 1.02,
    ["gary/erbil"] = 0.84,
    ["gary/established-on-final"] = 1.76,
    ["gary/evreux"] = 0.98,
    ["gary/expect"] = 1.02,
    ["gary/expect-vectors-to-runway"] = 1.95,
    ["gary/feet"] = 0.79,
    ["gary/five"] = 0.84,
    ["gary/fly-heading"] = 1.11,
    ["gary/fly-heading-climb"] = 1.11,
    ["gary/follow"] = 0.7,
    ["gary/for"] = 0.79,
    ["gary/ford"] = 0.79,
    ["gary/four"] = 0.84,
    ["gary/foxtrot"] = 1.07,
    ["gary/from"] = 0.74,
    ["gary/from-threshold"] = 1.35,
    ["gary/fujairah"] = 1.11,
    ["gary/gelendzhik"] = 1.07,
    ["gary/ghost"] = 0.98,
    ["gary/go-around-go-around"] = 1.81,
    ["gary/golf"] = 0.84,
    ["gary/good-afternoon"] = 1.16,
    ["gary/good-evening"] = 0.93,
    ["gary/good-morning"] = 1.02,
    ["gary/ground"] = 1.02,
    ["gary/gudauta"] = 1.07,
    ["gary/haifa"] = 0.93,
    ["gary/halab"] = 0.98,
    ["gary/hatay"] = 0.93,
    ["gary/hawg"] = 0.84,
    ["gary/hawk"] = 0.79,
    ["gary/hold"] = 0.88,
    ["gary/hotel"] = 0.93,
    ["gary/hundred"] = 0.91,
    ["gary/incirlik"] = 1.07,
    ["gary/increase-speed-to"] = 1.76,
    ["gary/india"] = 0.84,
    ["gary/initial"] = 0.93,
    ["gary/jedi"] = 0.93,
    ["gary/jiroft"] = 0.98,
    ["gary/juliet"] = 0.98,
    ["gary/kabul"] = 0.93,
    ["gary/kandahar"] = 1.07,
    ["gary/kerman"] = 0.88,
    ["gary/kilo"] = 0.93,
    ["gary/kirkuk"] = 0.98,
    ["gary/kish"] = 0.88,
    ["gary/knots"] = 0.88,
    ["gary/kobuleti"] = 1.25,
    ["gary/kolkhi"] = 0.88,
    ["gary/krasnodar"] = 1.21,
    ["gary/krymsk"] = 0.93,
    ["gary/kutaisi"] = 0.98,
    ["gary/lancer"] = 0.98,
    ["gary/landing"] = 1.02,
    ["gary/lar"] = 0.79,
    ["gary/lavan"] = 0.84,
    ["gary/left"] = 0.84,
    ["gary/lima"] = 0.93,
    ["gary/lincoln"] = 0.84,
    ["gary/lobo"] = 0.88,
    ["gary/lochini"] = 1.02,
    ["gary/maintain"] = 1.16,
    ["gary/mako"] = 0.88,
    ["gary/maktoum"] = 1.02,
    ["gary/maykop"] = 0.98,
    ["gary/MHz"] = 1.11,
    ["gary/mike"] = 0.79,
    ["gary/mineralnye"] = 1.21,
    ["gary/minhad"] = 1.07,
    ["gary/missed-approach"] = 1.25,
    ["gary/mozdok"] = 1.07,
    ["gary/murmansk"] = 1.07,
    ["gary/musa"] = 0.93,
    ["gary/nalchik"] = 1.02,
    ["gary/nautical-miles"] = 1.3,
    ["gary/niner"] = 0.88,
    ["gary/normandy"] = 0.98,
    ["gary/north"] = 0.86,
    ["gary/northeast"] = 1.1,
    ["gary/northwest"] = 1.15,
    ["gary/november"] = 1.02,
    ["gary/novorossiysk"] = 1.39,
    ["gary/number"] = 0.84,
    ["gary/of"] = 0.7,
    ["gary/olds"] = 0.88,
    ["gary/on"] = 0.65,
    ["gary/on-base-runway"] = 1.53,
    ["gary/on-downwind"] = 1.25,
    ["gary/one"] = 0.7,
    ["gary/on-this-frequency"] = 1.39,
    ["gary/oscar"] = 0.84,
    ["gary/out"] = 0.7,
    ["gary/ovda"] = 0.88,
    ["gary/panther"] = 0.93,
    ["gary/papa"] = 0.88,
    ["gary/pashkovsky"] = 1.21,
    ["gary/point"] = 0.84,
    ["gary/pontiac"] = 1.02,
    ["gary/qeshm"] = 0.79,
    ["gary/quebec"] = 0.93,
    ["gary/radar-contact"] = 1.39,
    ["gary/ramat"] = 0.88,
    ["gary/reaper"] = 0.84,
    ["gary/rebel"] = 0.74,
    ["gary/reduce-speed-to"] = 1.58,
    ["gary/report-15-NM"] = 2.14,
    ["gary/report-final"] = 1.35,
    ["gary/return-to-pattern"] = 2.65,
    ["gary/right"] = 0.79,
    ["gary/romeo"] = 0.98,
    ["gary/runway"] = 0.88,
    ["gary/runway-clear"] = 1.3,
    ["gary/runway-occupied"] = 1.49,
    ["gary/sakirpasa"] = 1.35,
    ["gary/senaki"] = 1.07,
    ["gary/seven"] = 0.79,
    ["gary/sharjah"] = 1.07,
    ["gary/shark"] = 0.93,
    ["gary/shiraz"] = 1.02,
    ["gary/sierra"] = 0.98,
    ["gary/sirri"] = 0.88,
    ["gary/six"] = 0.84,
    ["gary/slow-to-approach-speed"] = 1.72,
    ["gary/sniper"] = 0.93,
    ["gary/sochi"] = 0.93,
    ["gary/soganlug"] = 1.25,
    ["gary/south"] = 0.91,
    ["gary/southeast"] = 1.1,
    ["gary/southwest"] = 1.15,
    ["gary/speed"] = 0.93,
    ["gary/springfield"] = 1.16,
    ["gary/startup-clearance"] = 1.81,
    ["gary/storm"] = 0.93,
    ["gary/straight-in"] = 0.98,
    ["gary/sukhumi"] = 1.02,
    ["gary/taftanaz"] = 1.21,
    ["gary/talon"] = 0.88,
    ["gary/tango"] = 0.93,
    ["gary/tbilisi"] = 1.16,
    ["gary/thousand"] = 0.97,
    ["gary/three"] = 0.84,
    ["gary/tiger"] = 0.84,
    ["gary/to"] = 0.74,
    ["gary/tower"] = 0.88,
    ["gary/traffic"] = 0.88,
    ["gary/tunb"] = 0.88,
    ["gary/turn-final-heading"] = 1.39,
    ["gary/turn-left-heading"] = 1.39,
    ["gary/turn-right-heading"] = 1.39,
    ["gary/two"] = 0.7,
    ["gary/uniform"] = 0.98,
    ["gary/uzi"] = 0.79,
    ["gary/vacate-runway"] = 2.6,
    ["gary/vaziani"] = 1.16,
    ["gary/venom"] = 0.84,
    ["gary/victor"] = 0.84,
    ["gary/viper"] = 0.88,
    ["gary/vityazevo"] = 1.3,
    ["gary/vody"] = 0.84,
    ["gary/weasel"] = 0.93,
    ["gary/west"] = 0.86,
    ["gary/whiskey"] = 0.84,
    ["gary/wind"] = 0.88,
    ["gary/wind-calm"] = 1.21,
    ["gary/witch"] = 0.79,
    ["gary/with"] = 0.79,
    ["gary/wolf"] = 0.74,
    ["gary/xray"] = 0.93,
    ["gary/yankee"] = 0.88,
    ["gary/you"] = 0.84,
    ["gary/you-are-number"] = 1.3,
    ["gary/zero"] = 0.93,
    ["gary/zulu"] = 0.88,
}
-- PHRASE_DUR_END
ATC._PSUBS = ATC._PSUBS or {}
ATC._WSET = ATC._WSET or {}
ATC._NATO = ATC._NATO or {}
ATC._DWORDS = ATC._DWORDS or {}
ATC._CALLSIGNS = ATC._CALLSIGNS or {
    enfield=true, springfield=true, uzi=true, colt=true, dodge=true, ford=true, chevy=true, pontiac=true, lobo=true, hawg=true, olds=true, lincoln=true, jedi=true, viper=true, venom=true, witch=true, cobra=true, bone=true, mako=true, dude=true, tiger=true, wolf=true, weasel=true, panther=true, hawk=true, reaper=true, ghost=true, eagle=true, shark=true, sniper=true, lancer=true, devil=true, rebel=true, storm=true, talon=true
}
ATC.menuPaths = {}  -- [coalitionID] = { root, ground, tower, approach, departure }
function ATC.ensureMenusForCoalition(coalitionID)
    if not coalitionID then return end
    ATC.menuPaths[coalitionID] = ATC.menuPaths[coalitionID] or {}
end
ATC.config = {
        debug = true, -- General-purpose debug logging
    msgDuration        = 10,
    msgDurationLong    = 25,
    nearRadiusM        = 185200,
    radioTxPower       = 50000,
    radioModulation    = 0,
    gsAngleDeg         = 3.0,
    magvar             = 6,
    gsDeviationFt   = 200,
    guidanceInterval = 30,
    finalNM         = 20,
    stallWarnKt     = 80,
    approachSpeeds = {
        ["F-16C_50"]            = { clean=250, gear=190, final=160, maxFinal=200 },
        ["FA-18C_hornet"]       = { clean=250, gear=200, final=140, maxFinal=180 },
        ["F-15C"]               = { clean=250, gear=220, final=155, maxFinal=200 },
        ["F-15E"]               = { clean=250, gear=220, final=155, maxFinal=200 },
        ["F-14A-135-GR"]        = { clean=250, gear=210, final=134, maxFinal=180 },
        ["F-14B"]               = { clean=250, gear=210, final=134, maxFinal=180 },
        ["A-10C"]               = { clean=200, gear=160, final=130, maxFinal=160 },
        ["A-10C_2"]             = { clean=200, gear=160, final=130, maxFinal=160 },
        ["AV8BNA"]              = { clean=250, gear=200, final=110, maxFinal=150 },
        ["Su-27"]               = { clean=250, gear=210, final=145, maxFinal=190 },
        ["Su-33"]               = { clean=250, gear=210, final=145, maxFinal=190 },
        ["Su-25T"]              = { clean=200, gear=160, final=135, maxFinal=170 },
        ["Su-25"]               = { clean=200, gear=160, final=135, maxFinal=170 },
        ["MiG-29A"]             = { clean=250, gear=210, final=145, maxFinal=190 },
        ["MiG-29S"]             = { clean=250, gear=210, final=145, maxFinal=190 },
        ["MiG-21Bis"]           = { clean=250, gear=220, final=170, maxFinal=215 },
        ["AJS37"]               = { clean=250, gear=200, final=140, maxFinal=185 },
        ["M-2000C"]             = { clean=250, gear=210, final=155, maxFinal=195 },
        ["JF-17"]               = { clean=250, gear=210, final=145, maxFinal=185 },
        ["C-101CC"]             = { clean=200, gear=160, final=120, maxFinal=155 },
        ["L-39ZA"]              = { clean=200, gear=160, final=115, maxFinal=150 },
        ["Yak-52"]              = { clean=140, gear=110, final= 85, maxFinal=115 },
        ["TF-51D"]              = { clean=140, gear=110, final= 90, maxFinal=120 },
        ["P-51D-30-NA"]         = { clean=140, gear=110, final= 90, maxFinal=120 },
        ["Spitfire LF Mk. IXc"] = { clean=130, gear=100, final= 80, maxFinal=110 },
        ["FW-190D9"]            = { clean=170, gear=130, final=105, maxFinal=140 },
        ["Bf-109K-4"]           = { clean=160, gear=130, final=100, maxFinal=135 },
        ["Mi-8MT"]              = { clean=120, gear= 80, final= 55, maxFinal= 80 },
        ["Ka-50"]               = { clean=120, gear= 80, final= 50, maxFinal= 70 },
        ["Ka-50_3"]             = { clean=120, gear= 80, final= 50, maxFinal= 70 },
        ["UH-1H"]               = { clean=100, gear= 70, final= 50, maxFinal= 70 },
        ["SA342M"]              = { clean=100, gear= 70, final= 40, maxFinal= 60 },
        ["AH-64D_BLK_II"]       = { clean=120, gear= 80, final= 50, maxFinal= 70 },
        ["default"]             = { clean=250, gear=180, final=150, maxFinal=200 },
    },
    rootMenuLabel    = "ATC",
    menuRefreshLabel = "  Refresh Airfield List",
    refreshInterval = 10,
    queueBroadcastInterval = 30,
    vectoringInterval = 25,
    ilsHandoffNM = 8,
    defaultPatternAltFt = 1500,
    voiceDebug = true,
    voiceDebugToGroup = true,
    disableVoice = false, -- when true, disable tokenization and radioTransmission audio
    magvarCaucasus = 6,   -- Caucasus / Black Sea
    magvarPG = 2,         -- Persian Gulf
    magvarSyria = 4,      -- Syria
    magvarDefault = 0,    -- Default fallback
}

-- Normalization is deferred; called from onSimStart after airfields load.



function ATC.debugLog(msg)
    if not (ATC and ATC.config and ATC.config.debug) then return end
    ATC.log("DEBUG " .. tostring(msg))
end

function ATC.voiceDebug(groupId, msg)
    if not (ATC and ATC.config and ATC.config.voiceDebug) then return end
    local line = "VOICE " .. tostring(msg)
    ATC.log(line)
    -- Display is disabled; only log to file
end

local function fmtRadioList(radios)
    local parts = {}
    if not radios then return "none" end
    for idx = 1, 4 do
        local f = radios[idx]
        if f then
            parts[#parts + 1] = string.format("R%d=%.3f", idx, f)
        end
    end
    if #parts == 0 then return "none" end
    return table.concat(parts, ", ")
end
ATC.state = {
    aircraft  = {},   -- [unitName]    -> player record
    airfields = {},   -- [airbaseName] -> traffic record
    telemetry = {},   -- [unitName] -> { t, headingDeg, altAglFt, speedKt, aoaDeg, radios={[1..4]=mhz} }
}
function ATC.getFieldState(airbaseName)
    if not ATC.state.airfields[airbaseName] then
        ATC.state.airfields[airbaseName] = {
            landingSeq = {},
            departSeq  = {},
            rwyClear   = true,
            holdStack  = {},   -- [unitName] = assigned hold altitude (ft)
            patternSlots = {}, -- [unitName] = assigned pattern altitude (ft)
        }
    end
    return ATC.state.airfields[airbaseName]
end
function ATC.getOrCreateRecord(unitName, groupId)
    if not ATC.state.aircraft[unitName] then
        ATC.state.aircraft[unitName] = {
            groupId       = groupId,
            activeField   = nil,
            engagedField  = nil,  -- airfield player has an active request with
            phases        = {},
            cleared       = {},
            seqNum        = {},
            menuRoot      = nil,
            nearbyFields  = {},
            fieldMenus    = {},
            lastQueueMsg  = {},  -- [airbaseName] = timer.getTime() of last queue broadcast
            lastGuidance  = {},  -- [airbaseName] = timer.getTime() of last guidance call
            lastGSDev     = {},  -- [airbaseName] = "above"|"below"|"on" last deviation state
            patternLeg    = {},  -- [airbaseName] = "downwind"|"base"|"final"|nil
            lastVector    = {},  -- [airbaseName] = timer.getTime() of last vectoring call
            approachGate  = {},  -- [airbaseName] = current approach gate number (1,2,3,4...)
            stackAlt      = {},  -- [airbaseName] = assigned hold altitude (ft)
            landingCleared = {}, -- [airbaseName] = true once "cleared for approach/landing" issued
            finalCleared       = {}, -- [airbaseName] = true once final landing clearance issued
            gearReminded       = {}, -- [airbaseName] = true once gear/checkspeed reminder sent
            holdPhase          = {}, -- [airbaseName] = "inbound"|"outbound" racetrack leg
            patternCornerIdx   = {}, -- [airbaseName] = 1..#corners, which CRP to fly to next
            patternAlt         = {}, -- [airbaseName] = current stack altitude in ft (MSL)
            report15Done       = {}, -- [airbaseName] = true once pilot reported position at/inside 15 NM
            report15ReminderSent = {}, -- [airbaseName] = true once auto-reminder was sent at/inside 15 NM
            towerHandoffReady  = {}, -- [airbaseName] = true once CP5 crossed and handoff action should appear
            towerCheckedIn     = {}, -- [airbaseName] = true once pilot selected handoff to tower
            postLandingReady   = {}, -- [airbaseName] = true once landed and slowed for tower/ground handoff menu
            greeted            = {}, -- [airbaseName][controller] = true if greeted
            lastFreqRejection  = {}, -- [controllerType] = timer.getTime() of last frequency rejection message (silences duplicates)
        }
    end
    return ATC.state.aircraft[unitName]
end
function ATC.getDaytimeGreeting()
    local hour = 12
    if env and env.mission and env.mission.date and env.mission.start_time then
        local t = env.mission.start_time
        hour = math.floor((t / 3600) % 24)
    elseif timer and timer.getAbsTime then
        hour = math.floor((timer.getAbsTime() / 3600) % 24)
    end
    if hour < 12 then return "Good morning"
    elseif hour < 18 then return "Good afternoon"
    else return "Good evening" end
end
function ATC.getPhase(unitName, airbaseName)
    local rec = ATC.state.aircraft[unitName]
    if not rec then return "unknown" end
    return rec.phases[airbaseName] or "unknown"
end
local function getVoiceDuration(text, abName, controller)
    if ATC and ATC.config and ATC.config.disableVoice then
        return 0
    end
    local voice = "adam"
    if abName and controller then
        voice = ATC.getStationVoice(abName, controller)
    end
    local tokens = ATC.textToTokens(text)
    local total = 0
    for _, token in ipairs(tokens) do
        local phraseDur = ATC._phraseDur and ATC._phraseDur[voice .. "/" .. token] or 0.45
        total = total + phraseDur + 0.01 -- 10ms gap
    end
    return math.max(total, 2.0) -- never less than 2s
end
local function sendRadioVoice(groupId, abPos, text, abName, controller, dur)
    if not abPos or not abName or not controller then return end
    local ok, err = pcall(function()
        controller = controller or "Approach"
        local freqHz, modulation, power = ATC.getControllerRadio(abName, controller)
        local voice    = ATC.getStationVoice(abName, controller)
        local tokens   = ATC.textToTokens(text)
        local startT   = ATC.reserveRadioWindow(abName, controller, dur or ATC.ttsDuration(text))
        ATC.voiceDebug(groupId, string.format(
            "radioMsg %s/%s voice=%s freqHz=%s text='%s'",
            tostring(abName), tostring(controller), tostring(voice), tostring(freqHz), tostring(text)))
        ATC.scheduleTokens(groupId, abPos, freqHz, tokens, voice, startT, modulation, power)
    end)
    if not ok then
        ATC.log(string.format("WARN  sendRadioVoice fallback for %s/%s: %s",
            tostring(abName), tostring(controller), tostring(err)))
    end
end

function ATC.msg(groupId, text, long, abName, controller, skipVoice)
    local dur = long and ATC.config.msgDurationLong or ATC.config.msgDuration
    if abName and controller then
        local ok, result = pcall(getVoiceDuration, text, abName, controller)
        if ok and type(result) == "number" and result > 0 then
            dur = result
        else
            -- If voice is disabled or duration couldn't be computed, use long duration
            dur = ATC.config.msgDurationLong
            if not ok then
                ATC.log(string.format("WARN  msg duration fallback for %s/%s: %s",
                    tostring(abName), tostring(controller), tostring(result)))
            end
        end
    end
    trigger.action.outTextForGroup(groupId, text, dur, false)

    if not skipVoice and abName and controller then
        local ab = Airbase.getByName(abName)
        local abPos = ab and ATC.getAirbasePos(ab)
        sendRadioVoice(groupId, abPos, text, abName, controller, dur)
    end
end

function ATC.radioMsg(groupId, abPos, text, long, abName, controller)
    ATC.msg(groupId, text, long, abName, controller, true)
    sendRadioVoice(groupId, abPos, text, abName, controller, nil)
end

function ATC.radioMsgCustom(groupId, abPos, text, voiceText, long, abName, controller, skipVoice)
    local dur = long and ATC.config.msgDurationLong or ATC.config.msgDuration
    if abName and controller then
        local ok, result = pcall(getVoiceDuration, voiceText or text, abName, controller)
        if ok and type(result) == "number" and result > 0 then
            dur = result
        else
            dur = ATC.config.msgDurationLong
        end
    end
    trigger.action.outTextForGroup(groupId, text, dur, false)
    if not skipVoice and abName and controller then
        local pos = abPos
        if not pos then
            local ab = Airbase.getByName(abName)
            pos = ab and ATC.getAirbasePos(ab)
        end
        sendRadioVoice(groupId, pos, voiceText or text, abName, controller, dur)
    end
end
local function normalizeAirbaseName(name)
    if not name or name == "" then return nil end
    return string.lower(name):gsub("[^%w]", "")
end

local _AIRBASE_ALIASES = {
    ["sukhumibabushara"] = "Sukhumi",
    ["tbilisisoganlug"]  = "Soganlug",
}

local _SPOKEN_AIRBASE_NAME = {
    ["Anapa-Vityazevo"]      = "Anapa",
    ["Krasnodar-Center"]     = "Krasnodar",
    ["Krasnodar-Pashkovsky"] = "Krasnodar",
    ["Maykop-Khanskaya"]     = "Maykop",
    ["Senaki-Kolkhi"]        = "Senaki",
    ["Sochi-Adler"]          = "Sochi",
    ["Sukhumi-Babushara"]    = "Sukhumi",
    ["Tbilisi-Lochini"]      = "Tbilisi",
    ["Tbilisi-Soganlug"]     = "Tbilisi",
    ["Soganlug"]             = "Tbilisi",
}

function ATC.getSpokenAirbaseName(abName)
    if not abName or abName == "" then return "Airfield" end
    if _SPOKEN_AIRBASE_NAME[abName] then
        return _SPOKEN_AIRBASE_NAME[abName]
    end
    local canonical = _AIRBASE_ALIASES[normalizeAirbaseName(abName)]
    if canonical and _SPOKEN_AIRBASE_NAME[canonical] then
        return _SPOKEN_AIRBASE_NAME[canonical]
    end
    local first = tostring(abName):match("^([^%-]+)")
    return first or abName
end

function ATC.getRunway(abName)
    local rdata = (ATC.runways and next(ATC.runways) ~= nil) and ATC.runways or _runwaySnapshot
    if not rdata or not abName then
        ATC.debugLog(string.format("getRunway: abName=nil or rdata=nil (abName=%s)", tostring(abName)))
        return nil
    end
    local exact = rdata[abName]
    if exact then
        ATC.debugLog(string.format("getRunway: exact match for '%s'", tostring(abName)))
        return exact
    end

    local norm = normalizeAirbaseName(abName)
    ATC.debugLog(string.format("getRunway: normalized '%s' -> '%s'", tostring(abName), tostring(norm)))
    if not norm then return nil end

    local aliasKey = _AIRBASE_ALIASES[norm]
    if aliasKey and rdata[aliasKey] then
        ATC.debugLog(string.format("getRunway: aliasKey match '%s' -> '%s'", norm, aliasKey))
        return rdata[aliasKey]
    end

    for key, value in pairs(rdata) do
        if normalizeAirbaseName(key) == norm then
            ATC.debugLog(string.format("getRunway: normalized key match '%s' <-> '%s'", key, abName))
            return value
        end
    end

    ATC.debugLog(string.format("getRunway: no match for '%s' (norm='%s')", tostring(abName), tostring(norm)))
    return nil
end
function ATC.distVec3(a, b)
    if not a or not b or type(a.x) ~= "number" or type(b.x) ~= "number"
       or type(a.y) ~= "number" or type(b.y) ~= "number"
       or type(a.z) ~= "number" or type(b.z) ~= "number" then
        return math.huge
    end
    local dx = a.x - b.x
    local dy = a.y - b.y
    local dz = a.z - b.z
    return math.sqrt(dx*dx + dy*dy + dz*dz)
end
function ATC.distVec3H(a, b)
    if not a or not b or type(a.x) ~= "number" or type(b.x) ~= "number"
       or type(a.z) ~= "number" or type(b.z) ~= "number" then
        return math.huge
    end
    local dx = a.x - b.x
    local dz = a.z - b.z
    return math.sqrt(dx*dx + dz*dz)
end
function ATC.mToNM(m) return m / 1852 end
function ATC.mToFt(m) return m * 3.28084 end
function ATC.ordinal(n)
    if n == 1 then return "1st"
    elseif n == 2 then return "2nd"
    elseif n == 3 then return "3rd"
    else return n .. "th" end
end
function ATC.sequenceNumber(n)
    return tostring(n)
end
function ATC.getAirbasePos(ab)
    return ab:getPoint()
end
function ATC.getNearbyAirbases(centre, radiusM)
    local found = {}
    for _, side in ipairs({ coalition.side.BLUE,
                            coalition.side.RED,
                            coalition.side.NEUTRAL }) do
        local bases = coalition.getAirbases(side) or {}
        for _, ab in ipairs(bases) do
            local p = ATC.getAirbasePos(ab)
            if p then
                local d = ATC.distVec3H(centre, p)
                if d <= radiusM then
                    table.insert(found, { ab = ab, distM = d, name = ab:getName() })
                end
            end
        end
    end
    table.sort(found, function(a, b) return a.distM < b.distM end)
    return found
end
function ATC.getAltFt(unit)
    if not unit then return nil end
    local pos = unit:getPoint()
    if not pos then return nil end
    return math.floor(ATC.mToFt(pos.y))
end
function ATC.getAltAglFt(unit)
    if not unit then return nil end
    local pos = unit:getPoint()
    if not pos then return nil end
    local groundM = 0
    if land and land.getHeight then
        local ok, h = pcall(land.getHeight, { x = pos.x, y = pos.z })
        if ok and type(h) == "number" then
            groundM = h
        end
    end
    local aglM = pos.y - groundM
    return math.floor(ATC.mToFt(aglM))
end
function ATC.getSpeedKt(unit)
    if not unit then return nil end
    local vel = unit:getVelocity()
    if not vel then return nil end
    local spd = math.sqrt(vel.x*vel.x + vel.y*vel.y + vel.z*vel.z)
    return math.floor(spd * 1.94384)
end
function ATC.distUnitToBase(unit, ab)
    if not unit or not ab then return nil end
    local uPos = unit:getPoint()
    local bPos = ATC.getAirbasePos(ab)
    if not uPos or not bPos then return nil end
    return ATC.mToNM(ATC.distVec3H(uPos, bPos))
end
function ATC.isPlayer(unit)
    if not unit then return false end
    if not unit:isExist() then return false end
    local pName = unit:getPlayerName()
    if pName ~= nil and pName ~= "" then return true end
    for _, side in ipairs({ coalition.side.BLUE, coalition.side.RED, coalition.side.NEUTRAL }) do
        for _, pu in ipairs(coalition.getPlayers(side) or {}) do
            if pu and pu:getName() == unit:getName() then return true end
        end
    end
    return false
end
function ATC.getBearing(a, b)
    local dx = b.z - a.z    -- East component
    local dz = b.x - a.x    -- North component
    local brg = math.deg(math.atan2(dx, dz))
    if brg < 0 then brg = brg + 360 end
    return math.floor(brg + 0.5)
end
function ATC.getBearingText(a, b)
    if not a or not b then return nil end
    local bearing = ATC.getBearing(a, b)
    local sectors = {
        "north", "north-east", "east", "south-east",
        "south", "south-west", "west", "north-west",
    }
    local index = (math.floor(((bearing + 22.5) % 360) / 45) % 8) + 1
    return sectors[index], bearing
end
function ATC.getGSDeviationFt(unit, ab, gsAngle)
    if not unit or not ab then return nil end
    local uPos  = unit:getPoint()
    local bPos  = ATC.getAirbasePos(ab)
    if not uPos or not bPos then return nil end
    local distM  = ATC.distVec3H(uPos, bPos)
    local altM   = uPos.y - bPos.y          -- height above airbase elevation
    local ang    = gsAngle or ATC.config.gsAngleDeg
    local idealAltM  = distM * math.tan(math.rad(ang))
    local deviationM = altM - idealAltM
    return deviationM * 3.28084
end
function ATC.getGlideslope(unit, abPos, rwy)
    local result = { altDev = 0, speedDev = 0, aoaDev = 0 }
    if not unit or not abPos or not rwy then return result end
    local uPos = unit:getPoint()
    if not uPos then return result end
    local distM    = ATC.distVec3H(uPos, abPos)
    local altM     = uPos.y - abPos.y
    local gsAng    = ATC.config.gsAngleDeg or 3.0
    local idealAlt = distM * math.tan(math.rad(gsAng))
    local altErrFt = (altM - idealAlt) * 3.28084
    result.altDev  = altErrFt / (ATC.config.gsDeviationFt or 200)
    local spds = ATC.getApproachSpeeds(unit)
    if spds then
        local spdKt = ATC.getSpeedKt(unit) or 0
        local target = spds.final or 150
        result.speedDev = (spdKt - target) / math.max(target * 0.1, 10)
    end
    return result
end
function ATC.getApproachSpeeds(unit)
    if not unit then return ATC.config.approachSpeeds["default"] end
    local t = unit:getTypeName() or "default"
    return ATC.config.approachSpeeds[t]
        or ATC.config.approachSpeeds["default"]
end

function ATC.isOnFrequency(unitName, airbaseName, controller, opts)
    -- Check if player is tuned to the correct frequency
    -- controller = "approach", "tower", "ground", "departure"
    -- Returns true if on correct freq, false otherwise
    if not unitName or not airbaseName or not controller then return false end
    opts = opts or {}
    local rec = ATC.state.aircraft and ATC.state.aircraft[unitName]
    local groupId = rec and rec.groupId or nil
    local rwy = ATC.getRunway(airbaseName)
    if not rwy or not rwy.frequencies or not rwy.frequencies[controller] then
        ATC.voiceDebug(groupId, string.format(
            "%s %s missing runway frequency data",
            tostring(airbaseName), tostring(controller)))
        return false  -- No frequency defined for this controller
    end

    local requiredFreqMhz = rwy.frequencies[controller].mhz
    if not requiredFreqMhz then
        ATC.voiceDebug(groupId, string.format(
            "%s %s has nil required mhz",
            tostring(airbaseName), tostring(controller)))
        return false
    end

    -- Get current radio frequencies from telemetry
    local telem = ATC.state.telemetry and ATC.state.telemetry[unitName]
    local radios = telem and telem.radios
    local hasRadioData = radios and next(radios) ~= nil
    if not hasRadioData then
        -- No radio data from export hook (aircraft type may not expose frequencies,
        -- or LoGetSelfData().UnitName mismatch). Allow the request rather than
        -- blocking indefinitely.
        ATC.voiceDebug(groupId, string.format(
            "%s freq-check BYPASS (no radio data) controller=%s required=%.3f",
            tostring(unitName), tostring(controller), requiredFreqMhz))
        return true
    end

    -- Check if ANY radio is tuned to the correct frequency (±0.05 MHz tolerance)
    local tolerance = 0.05
    local matched = false
    for radioIdx = 1, 4 do
        local currentFreqMhz = radios[radioIdx]
        if currentFreqMhz and math.abs(currentFreqMhz - requiredFreqMhz) < tolerance then
            ATC.voiceDebug(groupId, string.format(
                "%s %s OK required=%.3f tuned=%.3f radios=[%s]",
                tostring(unitName), tostring(controller), requiredFreqMhz, currentFreqMhz, fmtRadioList(radios)))
            matched = true
            break
        end
    end
    if not matched then
        -- Log all tuned radios for debug
        local radioList = {}
        for radioIdx = 1, 4 do
            local f = radios[radioIdx]
            if f then
                table.insert(radioList, string.format("R%d=%.6f", radioIdx, f))
            end
        end
        ATC.voiceDebug(groupId, string.format(
            "%s %s FAIL required=%.6f radios=[%s]",
            tostring(unitName), tostring(controller), requiredFreqMhz, table.concat(radioList, ", ")))
    end
    return matched
end

function ATC.ttsClean(text)
    return (text:gsub("\n", "  "):gsub("%s+", " "):gsub("^ ", ""):gsub(" $", ""))
end
function ATC.toTrue(magHdg)
    return (magHdg + (ATC.config.magvar or 0)) % 360
end
function ATC.toMag(trueHdg)
    return (trueHdg - (ATC.config.magvar or 0) + 360) % 360
end
function ATC.ttsDuration(text)
    local clean = ATC.ttsClean(text)
    local words = select(2, clean:gsub("%S+", ""))
    return math.max(2, math.ceil(words / 2.5))   -- 2.5 wps
end
local _ATC_LOG_PATH = nil
function ATC.log(msg)
    local line = string.format("[%9.1f] %s", timer.getTime(), msg)
    if io and io.open then
        if not _ATC_LOG_PATH then
            local dir = (lfs and lfs.writedir and lfs.writedir()) or ""
            _ATC_LOG_PATH = dir .. "Logs\\DCS-atc.log"
        end
        local f = io.open(_ATC_LOG_PATH, "a")
        if f then
            f:write(line .. "\n")
            f:close()
            return
        end
    end
    if env and env.info then
        env.info("DCS-ATC " .. line)
    end
end
local _phraseSeqId = 0
local _missingVoiceClipLogged = {}
local function getPhraseAudioPath(voice, token)
    -- Always use .miz internal path for radioTransmission
    return string.format("AUDIO/atc/%s/%s.ogg", voice, token)
end

function ATC.getControllerRadio(abName, controller)
    local rwy     = ATC.runways and ATC.runways[abName]
    local freqs   = rwy and rwy.frequencies
    local ctrlKey = (controller or "Approach"):lower()
    local freqRec = freqs and freqs[ctrlKey]
    local fallback = freqs and freqs.approach
    local radio   = freqRec or fallback or {}
    local freqHz  = radio.hz or 251000000
    local modulation = radio.modulation
    if modulation == nil then
        modulation = ATC.config.radioModulation or 0
    end
    local power = radio.power or ATC.config.radioTxPower or 1000
    return freqHz, modulation, power
end

function ATC.scheduleTokens(groupId, abPos, freqHz, tokens, voice, startT, modulation, power)
    _phraseSeqId = _phraseSeqId + 1
    local seqId = _phraseSeqId
    ATC.voiceDebug(groupId, string.format(
        "TX seq=%d voice=%s tokens=%d", seqId, tostring(voice), #tokens))
    local t = startT
    local phraseDur = ATC._phraseDur or {}
    for i, token in ipairs(tokens) do
        local clipKey = voice .. "/" .. token
        local dur = phraseDur[clipKey] or 0.45  -- fallback duration for tokens without measured duration
        if not phraseDur[clipKey] then
            if not _missingVoiceClipLogged[clipKey] then
                _missingVoiceClipLogged[clipKey] = true
                ATC.log("WARN  VOICE missing dur: " .. tostring(clipKey))
            end
        end
        local name = string.format("ATC_%d_%d", seqId, i)
        local path = getPhraseAudioPath(voice, token)
        ATC.voiceDebug(groupId, string.format("TX %s %.2f", token, t))
        local _pos, _f, _n, _p, _m, _w = abPos, freqHz, name, path, modulation, power
        timer.scheduleFunction(function()
            trigger.action.radioTransmission(_p, _pos, _m, false, _f, _w, _n)
            return nil
        end, nil, t)
        t = t + dur + 0.005  -- 5 ms gap between clips (clips are silence-trimmed)
    end
end

-- Convert an altitude number to spoken word form: 4500 -> "four thousand five hundred"
local function altToWords(n)
    local dw = ATC._DWORDS or {}
    n = math.floor(tonumber(n) or 0)
    local th = math.floor(n / 1000)
    local hd = math.floor((n % 1000) / 100)
    if th > 0 and th <= 9 then
        local parts = { dw[th] or tostring(th), "thousand" }
        if hd > 0 then
            table.insert(parts, dw[hd] or tostring(hd))
            table.insert(parts, "hundred")
        end
        return table.concat(parts, " ")
    end
    -- fallback: digit by digit
    local parts = {}
    for d in tostring(n):gmatch(".") do
        table.insert(parts, dw[tonumber(d)] or d)
    end
    return table.concat(parts, " ")
end

function ATC.textToTokens(text)
    if ATC and ATC.config and ATC.config.disableVoice then return {} end
    if not text or text == "" then return {} end
    text = text:lower()
    text = text:gsub("[\n\r]", " ")
    text = text:gsub("%-", " ")
    for _, sub in ipairs(ATC._PSUBS or {}) do
        text = text:gsub(sub[1], sub[2])
    end
    -- Altitude: "4500 ft" -> "four thousand five hundred ft" (before ft->feet)
    text = text:gsub("(%d+) ft", function(n) return altToWords(n) .. " ft" end)
    -- NM distances: keep decimal as "point": "5.6 nm" -> "5 point 6 nm"
    text = text:gsub("(%d+)%.(%d+) nm", "%1 point %2 nm")
    text = text:gsub(" kt", " knots")
    text = text:gsub(" ft", " feet")
    text = text:gsub(" nm", " nautical-miles")
    -- General decimals (QFE, etc.): "29.83" -> "29 point 83"
    text = text:gsub("(%d+)%.(%d+)", "%1 point %2")
    text = text:gsub("[%.,!%;:%?%(%)%[%]]", " ")
    text = text:gsub("%s+", " ")
    text = text:gsub("^%s+", ""):gsub("%s+$", "")
    local tokens = {}
    -- Special handling for callsign + number at start
    local callsign, num, rest = text:match("^(%w+)%s+(%d%d)%s*(.*)$")
    if callsign and ATC._CALLSIGNS[callsign] then
        table.insert(tokens, callsign)
        for d in num:gmatch(".") do
            local dw = (ATC._DWORDS or {})[tonumber(d)]
            if dw then table.insert(tokens, dw) end
        end
        text = rest or ""
    end
    local wset = ATC._WSET or {}
    local csigns = ATC._CALLSIGNS or {}
    local dwords = ATC._DWORDS or {}
    for word in text:gmatch("[%w_%-]+") do
        if word:match("^__(.-)__$") then
            local chunk = word:match("^__(.-)__$"):gsub("_", "-")
            chunk = chunk:gsub("[^%w%-]", ""):gsub("%-+", "-"):gsub("^%-+", ""):gsub("%-+$", "")
            if chunk ~= "" then
                table.insert(tokens, chunk)
            end
        elseif word:match("^%d+$") then
            -- Split into individual digit tokens (ICAO: "one two zero")
            for d in word:gmatch(".") do
                local dw = dwords[tonumber(d)]
                if dw then table.insert(tokens, dw) end
            end
        elseif wset[word] then
            table.insert(tokens, word)
        elseif csigns[word] then
            table.insert(tokens, word)
        else
            -- Try to split mid-text callsign+number: "colt11" -> "colt","one","one"
            local alpha, digits = word:match("^(%a+)(%d+)$")
            if alpha and (csigns[alpha] or wset[alpha]) then
                if wset[alpha] or csigns[alpha] then
                    table.insert(tokens, alpha)
                end
                for d in digits:gmatch(".") do
                    local dw = dwords[tonumber(d)]
                    if dw then table.insert(tokens, dw) end
                end
            end
            -- else: unknown word, skip
        end
    end
    return tokens
end
local _PHRASE_VOICES = { "adam", "alice", "daniel", "gary" }
local _ROLE_VOICE = {
    approach  = "daniel",   -- British male, calm broadcaster
    tower     = "adam",     -- American male, firm authority
    ground    = "alice",    -- British female, professional
    departure = "gary",     -- Australian male, narrator
}
function ATC.getStationVoice(abName, role)
    local r = role and role:lower()
    if _ROLE_VOICE[r] then return _ROLE_VOICE[r] end
    local s = (abName or "") .. (role or "")
    local h = 0
    for i = 1, #s do h = h + string.byte(s, i) end
    return _PHRASE_VOICES[(h % #_PHRASE_VOICES) + 1]
end
local _RADIO_GAP_SEC = 0.35
local _radioBusyUntil = {}
function ATC.reserveRadioWindow(abName, controller, duration)
    local now = timer.getTime() + 0.05
    local key = string.format("%s|%s", abName or "ATC", (controller or "Approach"):lower())
    local startT = math.max(now, _radioBusyUntil[key] or 0)
    _radioBusyUntil[key] = startT + (duration or 2) + _RADIO_GAP_SEC
    return startT
end
-- The legacy radioMsg function body has been moved to the earlier definition at the top of this file.
-- Voice playback and scheduling logic removed for reimplementation
function ATC.roundHdg(h)
    local r = math.floor(h / 10 + 0.5) * 10 % 360
    return r == 0 and 360 or r
end
function ATC.fmtHdg(h)
    local r = math.floor(h + 0.5) % 360
    if r == 0 then r = 360 end
    return string.format("%03d", r)
end
local function angleDiff(a, b)
    local d = (b - a) % 360
    if d > 180 then d = d - 360 end
    return d
end
function ATC.getPatternLeg(uPos, abPos, rwy)
    local bearingToAc = ATC.getBearing(abPos, uPos)
    local diff = angleDiff(rwy.hdg, bearingToAc)
    local distNM = ATC.mToNM(ATC.distVec3H(uPos, abPos))
    if distNM <= 2  then return "short_final" end
    if distNM <= 8  then
        if math.abs(diff) <= 30 then return "final" end
        if math.abs(diff) <= 90 then return "base" end
    end
    if distNM > 15 then return "outbound" end
    if math.abs(math.abs(diff) - 180) <= 45 then return "downwind" end
    if math.abs(diff) > 90 then return "crosswind" end
    return "outbound"
end
function ATC.getArrivalReport(unit, airbaseName, ab)
    local report = {
        text = "inbound for landing",
        voice = "inbound for landing",
        traffic = "inbound for landing",
    }
    local rwy = ATC.getRunway(airbaseName)
    if not unit or not ab or not rwy then
        return report
    end
    local uPos = unit:getPoint()
    local abPos = ATC.getAirbasePos(ab)
    if not uPos or not abPos then
        return report
    end
    local distNM = ATC.mToNM(ATC.distVec3H(uPos, abPos))
    local leg = ATC.getPatternLeg(uPos, abPos, rwy)
    if leg == "short_final" or leg == "final" then
        report.text = "established on final"
        report.voice = "established on final"
        report.traffic = "established on final"
    elseif leg == "base" then
        report.text = "on base"
        report.voice = "on base, runway"
        report.traffic = "on base"
    elseif leg == "downwind" then
        report.text = "on downwind"
        report.traffic = "on downwind"
    elseif leg == "crosswind" then
        report.text = "crosswind"
        report.traffic = "crosswind"
    elseif leg == "outbound" then
        report.text = "inbound for landing"
        report.voice = "inbound for landing"
        report.traffic = "inbound for landing"
    end
    return report
end
function ATC.getInterceptHeading(uPos, abPos, rwy)
    local inboundTrueHdg = ATC.toTrue(rwy.hdg)          -- direction to fly to land
    local recipTrueHdg   = ATC.toTrue(rwy.reciprocal)   -- direction from field to FAP
    local inboundHdgRad  = math.rad(recipTrueHdg)
    local nm8m = 8 * 1852
    local entryPos  = {
        x = abPos.x + nm8m * math.cos(inboundHdgRad),
        y = abPos.y,
        z = abPos.z + nm8m * math.sin(inboundHdgRad),
    }
    local rawHdg = ATC.getBearing(uPos, entryPos)
    local diff = angleDiff(inboundTrueHdg, rawHdg)
    if diff >  30 then rawHdg = (inboundTrueHdg + 30) % 360 end
    if diff < -30 then rawHdg = (inboundTrueHdg - 30 + 360) % 360 end
    return ATC.roundHdg(rawHdg)
end
function ATC.getPatternAltFt(rwy, leg, distNM)
    local base = rwy.patternAlt or (rwy.elevation + ATC.config.defaultPatternAltFt)
    if leg == "downwind"   then return base end
    if leg == "base"       then return math.floor(base * 0.75) end
    if leg == "final"      then
        local distM  = distNM * 1852
        local gsAlt  = distM * math.tan(math.rad(ATC.config.gsAngleDeg))
        return math.max(rwy.elevation + 300, math.floor(rwy.elevation + ATC.mToFt(gsAlt)))
    end
    return base
end
ATC.config.holdAglBase   = ATC.config.holdAglBase  or 2500  -- floor of hold stack AGL
ATC.config.holdAglSep    = ATC.config.holdAglSep   or 1000  -- vertical separation between levels
ATC.config.holdMaxLevels = ATC.config.holdMaxLevels or 3    -- max hold levels
local HOLD_AGL_BASE   = ATC.config.holdAglBase
local HOLD_AGL_SEP    = ATC.config.holdAglSep
local HOLD_MAX_LEVELS = ATC.config.holdMaxLevels
local HOLD_SPEED      = 300   -- hold speed kt (uniform for all stack levels)
local HOLD_LEG_NM    = 5      -- outbound leg length NM
local FINAL_AGL      = 1500   -- altitude AGL at the final approach point (8 NM)
function ATC.getApproachGates(rwy, unit, startAlt)
    local spds = ATC.getApproachSpeeds(unit)
    local elev = rwy.elevation or 0
    local nearNM = ATC.config.ilsHandoffNM or 8
    startAlt = startAlt or (elev + HOLD_AGL_BASE)
    local gates = {}
    local startAGL  = startAlt - elev
    local maxAGL    = HOLD_AGL_BASE + (HOLD_MAX_LEVELS - 1) * HOLD_AGL_SEP
    local levelAGL  = math.min(math.ceil(startAGL / HOLD_AGL_SEP) * HOLD_AGL_SEP, maxAGL)
    while levelAGL >= HOLD_AGL_BASE do
        table.insert(gates, {
            altFt   = elev + levelAGL,
            speedKt = HOLD_SPEED,
            distNM  = nearNM + HOLD_LEG_NM,
            name    = "hold" .. levelAGL,
        })
        levelAGL = levelAGL - HOLD_AGL_SEP
    end
    table.insert(gates, {
        altFt   = elev + FINAL_AGL,
        speedKt = spds.final,
        distNM  = nearNM,
        name    = "final",
    })
    return gates
end
local function withinTolerance(actual, target, tolerance)
    if not actual or not target then return false end
    local delta = math.abs(actual - target)
    local maxDelta = target * tolerance
    return delta <= maxDelta
end
function ATC.checkGateCompliance(unit, gate, heading, isFinal)
    if not unit or not gate then return false end
    local altFt = ATC.getAltFt(unit)
    local spdKt = ATC.getSpeedKt(unit)
    local vel = unit:getVelocity()
    if not vel or not altFt or not spdKt then return false end
    local currentHdg = math.deg(math.atan2(vel.z, vel.x))
    if currentHdg < 0 then currentHdg = currentHdg + 360 end
    local hdgDiff = math.abs(currentHdg - heading)
    if hdgDiff > 180 then hdgDiff = 360 - hdgDiff end
    local tolerance = isFinal and 0.04 or 0.10  -- 4% for final, 10% for others
    local hdgToleranceDeg = isFinal and 15 or 30  -- degrees tolerance for heading
    local altOK = withinTolerance(altFt, gate.altFt, tolerance)
    local spdOK = withinTolerance(spdKt, gate.speedKt, tolerance)
    local hdgOK = hdgDiff <= hdgToleranceDeg
    if isFinal then
        return altOK and spdOK and hdgOK
    else
        local matchCount = 0
        if altOK then matchCount = matchCount + 1 end
        if spdOK then matchCount = matchCount + 1 end
        if hdgOK then matchCount = matchCount + 1 end
        return matchCount >= 2
    end
end
function ATC.determineCurrentGate(unit, rwy, gates, distNM, altFt)
    if not unit or not rwy or not gates or not distNM or not altFt then return 1 end
    for i = 1, #gates do
        local gate = gates[i]
        if distNM > gate.distNM then
            return i
        end
    end
    return #gates
end
function ATC.seqPos(unitName, airbaseName)
    local fs = ATC.state.airfields[airbaseName]
    if not fs then return 0 end
    for i, n in ipairs(fs.landingSeq) do
        if n == unitName then return i end
    end
    return 0
end
function ATC.addToLandingSeq(unitName, airbaseName)
    local fs  = ATC.getFieldState(airbaseName)
    local pos = ATC.seqPos(unitName, airbaseName)
    if pos > 0 then return pos end
    table.insert(fs.landingSeq, unitName)
    return #fs.landingSeq
end
function ATC.removeFromAllSeqs(unitName)
    for _, fs in pairs(ATC.state.airfields) do
        for i, n in ipairs(fs.landingSeq) do
            if n == unitName then table.remove(fs.landingSeq, i) break end
        end
        for i, n in ipairs(fs.departSeq) do
            if n == unitName then table.remove(fs.departSeq, i) break end
        end
    end
end
function ATC.removeRecord(unitName)
    local rec = ATC.state.aircraft[unitName]
    if not rec then return end
    ATC.removeFromAllSeqs(unitName)
    for abName, _ in pairs(ATC.state.airfields) do
        ATC.freeStackLevel(unitName, abName)
    end
    if rec.menuRoot then
        missionCommands.removeItemForGroup(rec.groupId, rec.menuRoot)
    end
    ATC.state.aircraft[unitName] = nil
    if ATC.state.telemetry then
        ATC.state.telemetry[unitName] = nil
    end
end
